clss1,group1 = divmod(32,5)
clss2,group2 = divmod(45,7)
clss3,group3 = divmod(51,6)
print("Number of students in each group:")
print("Class 1:", clss1)
print("Class 2:", clss2)
print("Class 3:", clss3)
print("Number of students leftover:")
print("Class 1:", group1)
print("Class 2:", group2)
print("Class 3:", group3)
